// Regenerate map.js from Natural Earth 1:50m (world-atlas TopoJSON).
// Output: window.WORLD_SVG string, viewBox "0 0 1000 507.209", <g id> = ISO alpha-2.
// Equirectangular projection, 1-decimal coordinate precision (no integer staircasing).

const fs = require("fs");
const path = require("path");
const { geoEquirectangular, geoPath } = require("d3-geo");
const { feature } = require("topojson-client");
const countriesIso = require("i18n-iso-countries");

const VIEW_W = 1000;
const VIEW_H = 507.209;

const topo = require("world-atlas/countries-50m.json");
const fc = feature(topo, topo.objects.countries);

// Equirectangular fit to the full viewBox (width-bound, vertically centered).
const projection = geoEquirectangular().fitSize([VIEW_W, VIEW_H], { type: "Sphere" });
// Default SVG-string path generator; .digits(1) rounds coords to 1 decimal.
const pathGen = geoPath(projection).digits(1);

// numeric ISO 3166 -> alpha-2
function alpha2(numericId) {
  const code = countriesIso.numericToAlpha2(String(numericId).padStart(3, "0"));
  return code || null;
}

// --- Outlier-territory clipping -------------------------------------------
// Natural Earth bundles distant overseas territories into a country's
// geometry (e.g. French Guiana / Réunion under FR), which wrecks the game's
// bbox-based auto-framing. Drop polygons that sit far from the country's main
// landmass, while keeping genuine archipelagos via transitive chaining: an
// island is kept if it's within OUTLIER_KM of any already-kept polygon.
const OUTLIER_KM = 1200;

function ringArea(ring) {
  let a = 0;
  for (let i = 0, n = ring.length, j = n - 1; i < n; j = i++) {
    a += ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1];
  }
  return Math.abs(a) / 2; // lon/lat units — fine for relative comparison
}

function haversineKm(a, b) {
  const R = 6371, rad = Math.PI / 180;
  const dLat = (b[1] - a[1]) * rad, dLon = (b[0] - a[0]) * rad;
  const s = Math.sin(dLat / 2) ** 2 +
    Math.cos(a[1] * rad) * Math.cos(b[1] * rad) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

// Coarsely sample an outer ring so nearest-distance checks stay cheap.
function sampleRing(ring) {
  const step = Math.max(1, Math.floor(ring.length / 24));
  const pts = [];
  for (let i = 0; i < ring.length; i += step) pts.push(ring[i]);
  return pts;
}

function minDist(sa, sb) {
  let m = Infinity;
  for (const p of sa) for (const q of sb) {
    const d = haversineKm(p, q);
    if (d < m) m = d;
  }
  return m;
}

// Returns geometry with outlier polygons removed (count of dropped polygons).
function clipOutliers(geometry) {
  const polys = geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  if (polys.length <= 1) return { geometry, dropped: 0 };

  const areas = polys.map((p) => ringArea(p[0]));
  const samples = polys.map((p) => sampleRing(p[0]));
  const kept = new Set([areas.indexOf(Math.max(...areas))]);

  let changed = true;
  while (changed) {
    changed = false;
    for (let i = 0; i < polys.length; i++) {
      if (kept.has(i)) continue;
      for (const k of kept) {
        if (minDist(samples[i], samples[k]) <= OUTLIER_KM) { kept.add(i); changed = true; break; }
      }
    }
  }
  if (kept.size === polys.length) return { geometry, dropped: 0 };
  const coords = [...kept].sort((a, b) => a - b).map((i) => polys[i]);
  return { geometry: { type: "MultiPolygon", coordinates: coords }, dropped: polys.length - kept.size };
}

const groups = [];
let skipped = [];
let clipped = [];
for (const f of fc.features) {
  const a2 = alpha2(f.id);
  if (!a2) { skipped.push(`${f.id}:${f.properties && f.properties.name}`); continue; }
  const { geometry, dropped } = clipOutliers(f.geometry);
  if (dropped) clipped.push(`${a2}(-${dropped})`);
  const d = pathGen({ type: "Feature", geometry });
  if (!d || !d.trim()) continue;
  groups.push(`<g id="${a2}"><path d="${d}"/></g>`);
}

const svg =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${VIEW_W} ${VIEW_H}" id="worldmap">` +
  groups.join("") +
  `</svg>`;

const out =
  "// World map (ISO alpha-2 <g> ids), Natural Earth 1:50m via world-atlas,\n" +
  "// equirectangular, 1-decimal precision. Generated by scripts/gen-map.js.\n" +
  "// Shipped as a string so the game runs from file:// without fetch/CORS.\n" +
  "window.WORLD_SVG = `" + svg + "`;\n";

fs.writeFileSync(path.join(__dirname, "..", "map.js"), out);
console.log(`Wrote map.js: ${groups.length} countries, ${(out.length / 1024).toFixed(0)} KB`);
if (skipped.length) console.log(`Skipped (no alpha-2): ${skipped.join(", ")}`);
if (clipped.length) console.log(`Clipped outlier territories: ${clipped.join(", ")}`);
